[versions]
androidDesugarJdkLibs = "2.1.3"
androidGradlePlugin = "8.6.0"
androidxComposeMaterial3 = "1.3.1"
androidxlifecycle = "2.8.7"
compose-bom = "2024.11.00"
androidxTestCore = "1.6.1"
coroutines = "1.9.0"
dagger = "2.52"
firebaseBom = "33.6.0"
junitJupiter = "5.11.3"
kotlin = "2.0.21"
kotlinxDatetime = "0.6.1"
navigation = "2.8.4"
navigationRuntimeKtx = "2.8.4"
runtimeAndroid = "1.7.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gms-googleServices = "com.google.gms.google-services:4.4.2"

# Plugins del dominio de build
app-android-application = { id = "app.android.application", version = "unspecified" }
app-android-application-compose = { id = "app.android.application.compose", version = "unspecified" }
app-android-library = { id = "app.android.library", version = "unspecified" }
app-android-library-compose = { id = "app.android.library.compose", version = "unspecified" }
app-android-hilt = { id = "app.android.hilt", version = "unspecified" }
app-android-feature = { id = "app.android.feature", version = "unspecified" }
app-jvm-library = { id = "app.jvm.library", version = "unspecified" }

[libraries]
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-junit = "androidx.test.ext:junit-ktx:1.2.1"
androidx-test-runner = "androidx.test:runner:1.6.2"
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-testmanifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-test = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
androidx-hilt-navigationcompose = "androidx.hilt:hilt-navigation-compose:1.2.0"
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-realtimedb = { group = "com.google.firebase", name = "firebase-database" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
truth = "com.google.truth:truth:1.4.4"
junit = "junit:junit:4.13.2"
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
robolectric = "org.robolectric:robolectric:4.13"
mockk = "io.mockk:mockk:1.13.13"

# Dependencias usadas en archivo build.gradle.kts de :build-domain
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }